namespace EventLand.Modules.PayPro.Entities;

/// <summary>
/// Represents a PayPro order / invoice created for online payment processing.
/// </summary>
public class Order
{
    public int Id { get; set; }

    /// <summary>
    /// Unique merchant order number (also used as idempotency key).
    /// </summary>
    public string OrderNumber { get; set; } = string.Empty;

    /// <summary>
    /// PayPro unique invoice / voucher identifier (assigned by PayPro upon successful creation).
    /// </summary>
    public string? PayProId { get; set; }

    /// <summary>
    /// Foreign key to registered Consumer, if order was created against a reusable consumer.
    /// </summary>
    public int? ConsumerId { get; set; }
    public Consumer? Consumer { get; set; }

    /// <summary>
    /// Optional foreign key to EventLand booking.
    /// </summary>
    public int? BookingId { get; set; }

    /// <summary>
    /// Total payable order amount.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Current lifecycle status of the order.
    /// </summary>
    public OrderStatus Status { get; set; } = OrderStatus.Pending;

    /// <summary>
    /// Date when invoice was issued.
    /// </summary>
    public DateTime IssueDate { get; set; } = DateTime.UtcNow.Date;

    /// <summary>
    /// Expiration / due date for payment.
    /// </summary>
    public DateTime DueDate { get; set; } = DateTime.UtcNow.Date.AddDays(1);

    /// <summary>
    /// Direct hosted card payment URL generated by PayPro.
    /// </summary>
    public string? Click2PayUrl { get; set; }

    /// <summary>
    /// Downloadable digital PDF invoice link provided by PayPro.
    /// </summary>
    public string? BillUrl { get; set; }

    /// <summary>
    /// Payment method mode used (e.g. "BAF" for Debit/Credit Card, "1Link" for Bank Transfer, "Nift").
    /// </summary>
    public string? PaymentMode { get; set; }

    /// <summary>
    /// Actual amount paid by the customer.
    /// </summary>
    public decimal? AmountPaid { get; set; }

    /// <summary>
    /// Timestamp when payment was completed and confirmed.
    /// </summary>
    public DateTime? DatePaid { get; set; }

    /// <summary>
    /// Full raw JSON response returned by PayPro at creation time.
    /// </summary>
    public string? RawCreateResponse { get; set; }

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
